# Update Metadata for New Experiments.

In [14]:
import numpy as np
import pandas as pd
import scanpy as sc

## Read Updated Metadata.

In [2]:
meta_path = "../../project_folder/data/gdrive/metadata_updated.xlsx"
meta_df = pd.read_excel(meta_path)
meta_df

,experiment_id,740-yp_[µm],mtg_[µm],rhflt3l_[ng_ml],experiment_number,gm-csf_[ng_ml],tpo_[ng_ml],sr1_[nm],um171_[nm],um729_[µm],...,source_id,hydrogel_type,o2_[%],source_cell_phenotype,total_count_beads,counts_source_cell_phenotype,days_of_culture,plate,absolute_number_multiplier_[2^n],cytometer_id
0,LPHO01,5,100,10,1.0,0,0.0,0.0,0.0,1.5,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,2.0,0,sonic
1,LPHO01,5,100,10,2.0,0,0.0,75.0,0.0,1.5,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,2.0,0,sonic
2,LPHO01,5,100,10,3.0,0,0.0,375.0,0.0,1.5,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,2.0,0,sonic
3,LPHO01,5,100,10,4.0,0,0.0,0.0,0.0,1.5,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,2.0,2,sonic
4,LPHO01,5,100,10,5.0,0,0.0,0.0,0.0,1.5,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,2.0,2,sonic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,LPHO013,5,100,10,223.0,8.7,2.5,755.2,1064.1,0.0,...,pooled,cellbind,13.5,CD34,1994.0,10000,14,1.0,1,sonic
281,LPHO013,5,100,10,224.0,8.7,2.5,754.3,1080.6,0.0,...,pooled,cellbind,13.5,CD34,1994.0,10000,14,1.0,2,sonic
282,LPHO013,5,100,10,225.0,9.2,2.2,997.3,1120.2,0.0,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic
283,LPHO013,5,100,10,226.0,8.6,2.4,927.9,735.6,0.2,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic
284,LPHO013,5,100,10,227.0,8.6,2.4,926.6,735.9,0.2,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic

### Get New Experiments.

In [11]:
meta_df_lpho013 = meta_df[
    meta_df.experiment_id == "LPHO013"
]
meta_df_lpho013

,experiment_id,740-yp_[µm],mtg_[µm],rhflt3l_[ng_ml],experiment_number,gm-csf_[ng_ml],tpo_[ng_ml],sr1_[nm],um171_[nm],um729_[µm],...,source_id,hydrogel_type,o2_[%],source_cell_phenotype,total_count_beads,counts_source_cell_phenotype,days_of_culture,plate,absolute_number_multiplier_[2^n],cytometer_id
273,LPHO013,5,100,10,216.0,0,0.00,0.00,66.54,0.0,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic
274,LPHO013,5,100,10,217.0,5.94,0.44,12.45,0.00,0.0,...,pooled,cellbind,10.0,CD34,1994.0,10000,14,1.0,1,sonic
275,LPHO013,5,100,10,218.0,6.83,0.55,21.97,0.26,0.0,...,pooled,cellbind,10.0,CD34,1994.0,10000,14,1.0,1,sonic
276,LPHO013,5,100,10,219.0,10.4,2.70,235.00,0.80,0.0,...,pooled,cellbind,10.0,CD34,1994.0,10000,14,1.0,1,sonic
277,LPHO013,5,100,10,220.0,9.1,2.20,173.50,0.20,0.0,...,pooled,cellbind,10.0,CD34,1994.0,10000,14,1.0,1,sonic
278,LPHO013,5,100,10,221.0,10.2,2.40,49.20,0.00,0.0,...,pooled,cellbind,13.5,CD34,1994.0,10000,14,1.0,1,sonic
279,LPHO013,5,100,10,222.0,7.1,3.40,579.20,1479.70,0.0,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic
280,LPHO013,5,100,10,223.0,8.7,2.50,755.20,1064.10,0.0,...,pooled,cellbind,13.5,CD34,1994.0,10000,14,1.0,1,sonic
281,LPHO013,5,100,10,224.0,8.7,2.50,754.30,1080.60,0.0,...,pooled,cellbind,13.5,CD34,1994.0,10000,14,1.0,2,sonic
282,LPHO013,5,100,10,225.0,9.2,2.20,997.30,1120.20,0.0,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic
283,LPHO013,5,100,10,226.0,8.6,2.40,927.90,735.60,0.2,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic
284,LPHO013,5,100,10,227.0,8.6,2.40,926.60,735.90,0.2,...,pooled,cellbind,20.0,CD34,1994.0,10000,14,1.0,1,sonic

### Map from Experiment Number to O2 and  #Days.

In [12]:
exp_number_to_O2 = {
    int(row["experiment_number"]): row["o2_[%]"]
    for _, row in meta_df_lpho013.iterrows()
}
exp_number_to_number_of_days = {
    int(row["experiment_number"]): row["days_of_culture"]
    for _, row in meta_df_lpho013.iterrows()
}
exp_number_to_O2, exp_number_to_number_of_days

({216: 20.0,
  217: 10.0,
  218: 10.0,
  219: 10.0,
  220: 10.0,
  221: 13.5,
  222: 20.0,
  223: 13.5,
  224: 13.5,
  225: 20.0,
  226: 20.0,
  227: 20.0},
 {216: 14,
  217: 14,
  218: 14,
  219: 14,
  220: 14,
  221: 14,
  222: 14,
  223: 14,
  224: 14,
  225: 14,
  226: 14,
  227: 14})

## Full Data.

### Read.

In [5]:
adata_full_path = "../../project_folder/data/gdrive/loop2/BloodPlus_Loop2_logicle.h5ad"
adata_full = sc.read_h5ad(adata_full_path)
adata_full

AnnData object with n_obs × n_vars = 4070966 × 20
    obs: 'experiment_number', 'replicate', 'date', 'cytometer', 'cytometer_serial_no', 'well_id', 'count_beads', 'cell_counts', 'experiment_id', '740-yp_[µm]', 'mtg_[µm]', 'rhflt3l_[ng_ml]', 'gm-csf_[ng_ml]', 'tpo_[ng_ml]', 'sr1_[nm]', 'um171_[nm]', 'um729_[µm]', 'scf_[ng_ml]', 'butyzamide_[nm]', 'retinoic_acid_[µm]', 'ldl_[ng_ml]', 'il3_[ng_ml]', 'source_id', 'hydrogel_type', 'o2_[%]', 'source_cell_phenotype', 'total_count_beads', 'counts_source_cell_phenotype', 'days_of_culture', 'plate', 'absolute_number_multiplier_[2^n]', 'cytometer_id', 'FSC-A :: FSC - Area', 'FSC-H :: FSC - Height', 'FSC-W :: FSC - Width', 'SSC-A :: SSC - Area', 'SSC-H :: SSC - Height', 'SSC-W :: SSC - Width', 'TIME', 'NA', 'AF Index', 'batch', '7-AAD'
    var: 'n', 'channel', 'marker', 'PnB', 'PnE', 'PnR', 'PnD', 'signal_type', 'antibody'
    uns: 'meta', 'processing_steps'
    layers: 'positives', 'raw'

### Update.

In [23]:
meta_full = adata_full.obs.copy()

lpho013_mask = meta_full.experiment_id == "LPHO013"
meta_full_lpho013 = meta_full[
    lpho013_mask
]

assert np.all(np.isfinite(meta_full_lpho013["o2_[%]"].values))
assert np.all(np.isfinite(meta_full_lpho013["days_of_culture"].values))

meta_full_lpho013["o2_[%]"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_O2)
meta_full_lpho013["days_of_culture"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_number_of_days)

assert np.all(np.isfinite(meta_full_lpho013["o2_[%]"].values))
assert np.all(np.isfinite(meta_full_lpho013["days_of_culture"].values))

print("BEFORE: ", meta_full["o2_[%]"].unique())
print("BEFORE: ", meta_full["days_of_culture"].unique())

meta_full.loc[lpho013_mask, "o2_[%]"] = meta_full_lpho013["o2_[%]"].values
meta_full.loc[lpho013_mask, "days_of_culture"] = meta_full_lpho013["days_of_culture"].values

assert np.all(np.isfinite(meta_full["o2_[%]"].values))
assert np.all(np.isfinite(meta_full["days_of_culture"].values))

print("AFTER: ", meta_full["o2_[%]"].unique())
print("AFTER: ", meta_full["days_of_culture"].unique())

adata_full.obs = meta_full

BEFORE:  [19.04  9.26  9.73 10.2  10.7  13.4  19.1  13.5  20.1  20.2 ]
BEFORE:  [13.24 14.54 16.98 17.3  18.1  12.   14.   16.4  13.1 ]
AFTER:  [20.  10.  13.5]
AFTER:  [14.]

### Write.

In [24]:
adata_full_path_output = "../../project_folder/output/miscellaneous_new/meta_update_BloodPlus_Loop2_logicle.h5ad"
adata_full.write_h5ad(adata_full_path_output)

## 500k Subset.

### Read.

In [7]:
adata_500k_path = "../../project_folder/data/gdrive/loop2/BloodPlus_Loop2_logicle_500k.h5ad"
adata_500k = sc.read_h5ad(adata_500k_path)
adata_500k

AnnData object with n_obs × n_vars = 499992 × 20
    obs: 'experiment_number', 'replicate', 'date', 'cytometer', 'cytometer_serial_no', 'well_id', 'count_beads', 'cell_counts', 'experiment_id', '740-yp_[µm]', 'mtg_[µm]', 'rhflt3l_[ng_ml]', 'gm-csf_[ng_ml]', 'tpo_[ng_ml]', 'sr1_[nm]', 'um171_[nm]', 'um729_[µm]', 'scf_[ng_ml]', 'butyzamide_[nm]', 'retinoic_acid_[µm]', 'ldl_[ng_ml]', 'il3_[ng_ml]', 'source_id', 'hydrogel_type', 'o2_[%]', 'source_cell_phenotype', 'total_count_beads', 'counts_source_cell_phenotype', 'days_of_culture', 'plate', 'absolute_number_multiplier_[2^n]', 'cytometer_id', 'FSC-A :: FSC - Area', 'FSC-H :: FSC - Height', 'FSC-W :: FSC - Width', 'SSC-A :: SSC - Area', 'SSC-H :: SSC - Height', 'SSC-W :: SSC - Width', 'TIME', 'NA', 'AF Index', 'batch', '7-AAD', 'cell_type', 'Experiment_type'
    var: 'n', 'channel', 'marker', 'PnB', 'PnE', 'PnR', 'PnD', 'signal_type', 'antibody'
    uns: 'meta', 'neighbors', 'processing_steps', 'umap'
    obsm: 'X_umap'
    layers: 'positives', 'raw'
    obsp: 'connectivities', 'distances'

### Update.

In [25]:
meta_full = adata_500k.obs.copy()

lpho013_mask = meta_full.experiment_id == "LPHO013"
meta_full_lpho013 = meta_full[
    lpho013_mask
]

assert np.all(np.isfinite(meta_full_lpho013["o2_[%]"].values))
assert np.all(np.isfinite(meta_full_lpho013["days_of_culture"].values))

meta_full_lpho013["o2_[%]"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_O2)
meta_full_lpho013["days_of_culture"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_number_of_days)

assert np.all(np.isfinite(meta_full_lpho013["o2_[%]"].values))
assert np.all(np.isfinite(meta_full_lpho013["days_of_culture"].values))

print("BEFORE: ", meta_full["o2_[%]"].unique())
print("BEFORE: ", meta_full["days_of_culture"].unique())

meta_full.loc[lpho013_mask, "o2_[%]"] = meta_full_lpho013["o2_[%]"].values
meta_full.loc[lpho013_mask, "days_of_culture"] = meta_full_lpho013["days_of_culture"].values

assert np.all(np.isfinite(meta_full["o2_[%]"].values))
assert np.all(np.isfinite(meta_full["days_of_culture"].values))

print("AFTER: ", meta_full["o2_[%]"].unique())
print("AFTER: ", meta_full["days_of_culture"].unique())

adata_500k.obs = meta_full

BEFORE:  [13.4   9.73 20.1  19.1  13.5  19.04 10.2  10.7   9.26 20.2 ]
BEFORE:  [14.   16.98 16.4  12.   18.1  13.24 13.1  17.3  14.54]
AFTER:  [13.5 10.  20. ]
AFTER:  [14.]

### Write.

In [26]:
adata_500k_path_output = "../../project_folder/output/miscellaneous_new/meta_update_BloodPlus_Loop2_logicle_500k.h5ad"
adata_500k.write_h5ad(adata_500k_path_output)

## Concatenate with Old Data from Loop 1.

### Read Full Adata from Loop 1.

In [8]:
adata_full_orig_path = "../../project_folder/data/gdrive/new_dataset/BloodPlus_Logicle_pm_.h5ad"
adata_full_orig = sc.read_h5ad(adata_full_orig_path)
adata_full_orig

AnnData object with n_obs × n_vars = 52085765 × 20
    obs: 'experiment_number', 'replicate', 'date', 'cytometer', 'cytometer_serial_no', 'well_id', 'count_beads', 'cell_counts', 'experiment_id', '740-yp_[µm]', 'mtg_[µm]', 'rhflt3l_[ng_ml]', 'gm-csf_[ng_ml]', 'tpo_[ng_ml]', 'sr1_[nm]', 'um171_[nm]', 'um729_[µm]', 'scf_[ng_ml]', 'butyzamide_[nm]', 'retinoic_acid_[µm]', 'ldl_[ng_ml]', 'il3_[ng_ml]', 'source_id', 'hydrogel_type', 'o2_[%]', 'source_cell_phenotype', 'total_count_beads', 'counts_source_cell_phenotype', 'days_of_culture', 'plate', 'absolute_number_multiplier_[2^n]', 'cytometer_id', 'FSC-A :: FSC - Area', 'FSC-H :: FSC - Height', 'FSC-W :: FSC - Width', 'SSC-A :: SSC - Area', 'SSC-H :: SSC - Height', 'SSC-W :: SSC - Width', 'TIME', 'NA', 'AF Index', 'batch', '7-AAD'
    var: 'n', 'channel', 'marker', 'PnB', 'PnE', 'PnR', 'PnD', 'signal_type', 'antibody'
    uns: 'meta', 'processing_steps'
    layers: 'positives', 'raw'

### Concatenate.

In [27]:
adata_full_concat = sc.concat((adata_full_orig, adata_full), merge="same", uns_merge="same")
adata_full_concat

/lustre/groups/ml01/workspace/lorenzo.consoli/micromamba/envs/sc_exp_design/lib/python3.12/site-packages/anndata/_core/anndata.py:1878: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

AnnData object with n_obs × n_vars = 56156731 × 20
    obs: 'experiment_number', 'replicate', 'date', 'cytometer', 'cytometer_serial_no', 'well_id', 'count_beads', 'cell_counts', 'experiment_id', '740-yp_[µm]', 'mtg_[µm]', 'rhflt3l_[ng_ml]', 'gm-csf_[ng_ml]', 'tpo_[ng_ml]', 'sr1_[nm]', 'um171_[nm]', 'um729_[µm]', 'scf_[ng_ml]', 'butyzamide_[nm]', 'retinoic_acid_[µm]', 'ldl_[ng_ml]', 'il3_[ng_ml]', 'source_id', 'hydrogel_type', 'o2_[%]', 'source_cell_phenotype', 'total_count_beads', 'counts_source_cell_phenotype', 'days_of_culture', 'plate', 'absolute_number_multiplier_[2^n]', 'cytometer_id', 'FSC-A :: FSC - Area', 'FSC-H :: FSC - Height', 'FSC-W :: FSC - Width', 'SSC-A :: SSC - Area', 'SSC-H :: SSC - Height', 'SSC-W :: SSC - Width', 'TIME', 'NA', 'AF Index', 'batch', '7-AAD'
    var: 'n', 'channel', 'marker', 'PnB', 'PnE', 'PnR', 'PnD', 'signal_type', 'antibody'
    uns: 'meta', 'processing_steps'
    layers: 'positives', 'raw'

### Make Observation Names Unique.

In [29]:
adata_full_concat.obs_names_make_unique()

### Update Fields.

In [30]:
meta_full = adata_full_concat.obs.copy()

lpho013_mask = meta_full.experiment_id == "LPHO013"
meta_full_lpho013 = meta_full[
    lpho013_mask
]

assert np.all(np.isfinite(meta_full_lpho013["o2_[%]"].values))
assert np.all(np.isfinite(meta_full_lpho013["days_of_culture"].values))

meta_full_lpho013["o2_[%]"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_O2)
meta_full_lpho013["days_of_culture"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_number_of_days)

assert np.all(np.isfinite(meta_full_lpho013["o2_[%]"].values))
assert np.all(np.isfinite(meta_full_lpho013["days_of_culture"].values))

print("BEFORE: ", meta_full["o2_[%]"].unique())
print("BEFORE: ", meta_full["days_of_culture"].unique())

meta_full.loc[lpho013_mask, "o2_[%]"] = meta_full_lpho013["o2_[%]"].values
meta_full.loc[lpho013_mask, "days_of_culture"] = meta_full_lpho013["days_of_culture"].values

assert np.all(np.isfinite(meta_full["o2_[%]"].values))
assert np.all(np.isfinite(meta_full["days_of_culture"].values))

print("AFTER: ", meta_full["o2_[%]"].unique())
print("AFTER: ", meta_full["days_of_culture"].unique())

adata_full_concat.obs = meta_full

/tmp/ipykernel_3700046/2985129553.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta_full_lpho013["o2_[%]"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_O2)
/tmp/ipykernel_3700046/2985129553.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  meta_full_lpho013["days_of_culture"] = meta_full_lpho013.experiment_number.astype(int).map(exp_number_to_number_of_days)

BEFORE:  [20.  10.  13.5]
BEFORE:  [13. 21. 36. 15. 27. 14. 28.]
AFTER:  [20.  10.  13.5]
AFTER:  [13. 21. 36. 15. 27. 14. 28.]

### Update DType.

In [31]:
adata_full_concat.obs.experiment_number = adata_full_concat.obs.experiment_number.astype(int)
adata_full_concat.obs.count_beads = adata_full_concat.obs.count_beads.astype(int)
adata_full_concat.obs.cell_counts = adata_full_concat.obs.cell_counts.astype(int)

### Write.

In [32]:
adata_full_concat_path = "../../project_folder/output/miscellaneous_new/concat_BloodPlus_logicle_Loop2.h5ad"
adata_full_concat.write_h5ad(adata_full_concat_path)
adata_full_concat

AnnData object with n_obs × n_vars = 56156731 × 20
    obs: 'experiment_number', 'replicate', 'date', 'cytometer', 'cytometer_serial_no', 'well_id', 'count_beads', 'cell_counts', 'experiment_id', '740-yp_[µm]', 'mtg_[µm]', 'rhflt3l_[ng_ml]', 'gm-csf_[ng_ml]', 'tpo_[ng_ml]', 'sr1_[nm]', 'um171_[nm]', 'um729_[µm]', 'scf_[ng_ml]', 'butyzamide_[nm]', 'retinoic_acid_[µm]', 'ldl_[ng_ml]', 'il3_[ng_ml]', 'source_id', 'hydrogel_type', 'o2_[%]', 'source_cell_phenotype', 'total_count_beads', 'counts_source_cell_phenotype', 'days_of_culture', 'plate', 'absolute_number_multiplier_[2^n]', 'cytometer_id', 'FSC-A :: FSC - Area', 'FSC-H :: FSC - Height', 'FSC-W :: FSC - Width', 'SSC-A :: SSC - Area', 'SSC-H :: SSC - Height', 'SSC-W :: SSC - Width', 'TIME', 'NA', 'AF Index', 'batch', '7-AAD'
    var: 'n', 'channel', 'marker', 'PnB', 'PnE', 'PnR', 'PnD', 'signal_type', 'antibody'
    uns: 'meta', 'processing_steps'
    layers: 'positives', 'raw'